### ISSUE TITLE
Adding blogs.denverpost.com to webmaster tools

### ISSUE THREAD

**Issue by danielpetty** [schneidan/thespot#5]
Need to add blogs.denverpost.com to Google webmaster tools for Denver Post. This is the code:
```
<meta name="google-site-verification" content="2bKNvyyGh6DUlOvH1PYsmKN4KRlb-0ZI7TvFtuKLeAc" />
```

**Comment by freejoe76** [comment]
Note: wrap your markup in three backticks, per https://guides.github.com/features/mastering-markdown/

**Comment by freejoe76** [comment]
Okay this is done.
