### ISSUE TITLE
Outbrain titles are misaligned, Outbrain credit's appearing twice

### ISSUE THREAD

**Issue by freejoe76** [schneidan/thespot#7]
http://blogs.denverpost.com/rapids/2015/01/30/colorado-rapids-preseason-schedule-2015/26661/#dpArticleTabs

**Comment by schneidan** [comment]
Issue is part CSS conflict and part Outbrain widget issue. I have fixed the CSS conflict and notified Outbrain of the widget misconfiguration.

**Comment by freejoe76** [comment]
Thanks Dan!
